name: validation
on:
  - push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Prepare
        run: composer install
      - name: Lint
        run: composer lint
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        php-versions: ['8.1', '8.2']
    needs:
      - lint
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Prepare
        run: make provision
      - name: Test
        run: docker compose exec -T --workdir=/opt/drall -e XDEBUG_MODE=coverage main make test
      - name: Coverage
        run: make coverage-report/text
