name: validation
on:
  - push
env:
  DRUPAL_PATH: /opt/drupal
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php-versions: ['8.1']
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Path Setup
        run: |
          echo "/opt/drall/bin" >> $GITHUB_PATH
          echo "/opt/drall/vendor/bin" >> $GITHUB_PATH
      - name: Prepare
        run: |
          cp -r . /opt/drall
          make provision
        shell: bash
      - name: Lint
        run: make lint
        shell: bash
      - name: Test
        run: make test
        shell: bash
      - name: Coverage
        run: make coverage-report/text
        shell: bash
